### ISSUE TITLE
Auto format on save

### ISSUE THREAD

**Issue by BWBama85** [ObliviousHarmony/vscode-php-codesniffer#74] opened 2023-04-27 20:16 UTC
### Problem Description

First off, thank you for putting in the time to provide an updated sniffer for VSCode. I come from PHP Sniffer & Beautifier and I mostly want to make sure that I have things set up correctly.

With PHP Sniffer & Beautifier, I could set it so that it would format the document when I saved the file. I notice with your extension, there is a setting to change the Lint Action. 

From what I can tell, this only runs the Linter to check if there are issues with the code and does not format the code.

1) Is there a feature I am missing here that will automatically format the code when I save the file? 
2) If not, can this feature be added.

### Proposed Solution

When I save the file, I would like the document to format and fix issues that it can.

**Comment by ObliviousHarmony** [comment] 2023-04-27 20:32
Hi @BWBama85,

This is a duplicate of https://github.com/ObliviousHarmony/vscode-php-codesniffer/issues/41.

I avoided adding this as a feature because it is something that VS Code already supports natively.

**Closed** 2023-04-27 20:32 UTC
